### ISSUE TITLE
testing-framework pipeline is broken

### ISSUE THREAD

**Issue by lmilbaum** [containers/ai-lab-recipes#327]

**Comment by lmilbaum** [comment]
It is green now. Was something changed? What can we do to prevent those?

**Comment by Gregory-Pereira** [comment]
After fixing the issue discussed yesterday with the `bootc` parent images not having a `x86_64` manifest in its manifest list (see issue thread: https://redhat-internal.slack.com/archives/C06S75ZF9JT/p1713891339910709) the tests generally pass now. I say generally because I did still see model download timeouts ([see an example](https://github.com/containers/ai-lab-recipes/actions/runs/8811838822/job/24186451334#step:9:31)) which cause failure but you can just re-run those jobs after 10 ish minutes and they will pass This does require user knowledge of the issue though, and it makes our success rate about 85% on tests that should pass due to long download times.

**Comment by rhatdan** [comment]
Let's expand the timeouts.

**Comment by Gregory-Pereira** [comment]
Quick fix below in #329 but this is just another instance where moving to self-hosted runners would be helpful.

**Comment by lmilbaum** [comment]
> Quick fix below in [#329](https://github.com/containers/ai-lab-recipes/pull/329) but this is just another instance where moving to self-hosted runners would be helpful.

Can we move the self-hosted runners issue to the Todo status?

**Comment by Gregory-Pereira** [comment]
Resolved with quickfix #329 but real change is in #264
