### ISSUE TITLE
https://quay.io/repository/ai-lab/llamacpp-python-vulkan is provided only for aarch64

### ISSUE THREAD

**Issue by jeffmaury** [containers/ai-lab-recipes#526]

**Comment by Gregory-Pereira** [comment]
~~I think you mean its only provided for `amd64` and not for `arm64`. I will add a build for it now.~~ I was looking at the Cuda image workflow, however this is the vulkan image and it was pushed by hand instead of workflow, updating the CI for this.

**Comment by Gregory-Pereira** [comment]
So it turns out that the container file is hardcoded for installation on AARCH64, it needs to be re-written to support amd64. That makes this a 2 step process, the original PR I will rework to just fix automated builds on Aarch64 and then a second one to refactor the containerfile to build for both.

**Comment by Gregory-Pereira** [comment]
Code has been merged, images coming soon.
